[package]
name = "v4l2-sys-vendored"
version = "0.1.0"
edition = "2021"

links = "v4l2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
cc = "1.0"
pkg-config = "0.3.27"
bindgen = "0.65.1"
anyhow = "1.0.71"

